# Generated by Django 3.1.1 on 2020-11-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201106_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Lowend', 'Lowend'), ('Highend', 'Highend')], max_length=200, null=True),
        ),
    ]
